# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.market_api import MarketApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = MarketApi()
    yield api


class TestMarketApi:
    """MarketApi unit test stubs"""

    def test_get_characters_character_id_orders(self, api):
        """Test case for get_characters_character_id_orders

        List open orders from a character
        """
        pass

    def test_get_characters_character_id_orders_history(self, api):
        """Test case for get_characters_character_id_orders_history

        List historical orders by a character
        """
        pass

    def test_get_corporations_corporation_id_orders(self, api):
        """Test case for get_corporations_corporation_id_orders

        List open orders from a corporation
        """
        pass

    def test_get_corporations_corporation_id_orders_history(self, api):
        """Test case for get_corporations_corporation_id_orders_history

        List historical orders from a corporation
        """
        pass

    def test_get_markets_groups(self, api):
        """Test case for get_markets_groups

        Get item groups
        """
        pass

    def test_get_markets_groups_market_group_id(self, api):
        """Test case for get_markets_groups_market_group_id

        Get item group information
        """
        pass

    def test_get_markets_prices(self, api):
        """Test case for get_markets_prices

        List market prices
        """
        pass

    def test_get_markets_region_id_history(self, api):
        """Test case for get_markets_region_id_history

        List historical market statistics in a region
        """
        pass

    def test_get_markets_region_id_orders(self, api):
        """Test case for get_markets_region_id_orders

        List orders in a region
        """
        pass

    def test_get_markets_region_id_types(self, api):
        """Test case for get_markets_region_id_types

        List type IDs relevant to a market
        """
        pass

    def test_get_markets_structures_structure_id(self, api):
        """Test case for get_markets_structures_structure_id

        List orders in a structure
        """
        pass
