# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.contracts_api import ContractsApi


@pytest.fixture(scope="module")
def api():
    api = ContractsApi()
    yield api


class TestContractsApi:
    """ContractsApi unit test stubs"""

    def test_get_characters_character_id_contracts(self, api):
        """Test case for get_characters_character_id_contracts

        Get contracts
        """
        pass

    def test_get_characters_character_id_contracts_contract_id_bids(self, api):
        """Test case for get_characters_character_id_contracts_contract_id_bids

        Get contract bids
        """
        pass

    def test_get_characters_character_id_contracts_contract_id_items(self, api):
        """Test case for get_characters_character_id_contracts_contract_id_items

        Get contract items
        """
        pass

    def test_get_contracts_public_bids_contract_id(self, api):
        """Test case for get_contracts_public_bids_contract_id

        Get public contract bids
        """
        pass

    def test_get_contracts_public_items_contract_id(self, api):
        """Test case for get_contracts_public_items_contract_id

        Get public contract items
        """
        pass

    def test_get_contracts_public_region_id(self, api):
        """Test case for get_contracts_public_region_id

        Get public contracts
        """
        pass

    def test_get_corporations_corporation_id_contracts(self, api):
        """Test case for get_corporations_corporation_id_contracts

        Get corporation contracts
        """
        pass

    def test_get_corporations_corporation_id_contracts_contract_id_bids(self, api):
        """Test case for get_corporations_corporation_id_contracts_contract_id_bids

        Get corporation contract bids
        """
        pass

    def test_get_corporations_corporation_id_contracts_contract_id_items(self, api):
        """Test case for get_corporations_corporation_id_contracts_contract_id_items

        Get corporation contract items
        """
        pass
