# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.search_api import SearchApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = SearchApi()
    yield api


class TestSearchApi:
    """SearchApi unit test stubs"""

    def test_get_characters_character_id_search(self, api):
        """Test case for get_characters_character_id_search

        Search on a string
        """
        pass

    def test_get_search(self, api):
        """Test case for get_search

        Search on a string
        """
        pass
