# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.assets_api import AssetsApi


@pytest.fixture(scope="module")
def api():
    api = AssetsApi()
    yield api


class TestAssetsApi:
    """AssetsApi unit test stubs"""

    def test_get_characters_character_id_assets(self, api):
        """Test case for get_characters_character_id_assets

        Get character assets
        """
        pass

    def test_get_corporations_corporation_id_assets(self, api):
        """Test case for get_corporations_corporation_id_assets

        Get corporation assets
        """
        pass

    def test_post_characters_character_id_assets_locations(self, api):
        """Test case for post_characters_character_id_assets_locations

        Get character asset locations
        """
        pass

    def test_post_characters_character_id_assets_names(self, api):
        """Test case for post_characters_character_id_assets_names

        Get character asset names
        """
        pass

    def test_post_corporations_corporation_id_assets_locations(self, api):
        """Test case for post_corporations_corporation_id_assets_locations

        Get corporation asset locations
        """
        pass

    def test_post_corporations_corporation_id_assets_names(self, api):
        """Test case for post_corporations_corporation_id_assets_names

        Get corporation asset names
        """
        pass
