# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.industry_api import IndustryApi


@pytest.fixture(scope="module")
def api():
    api = IndustryApi()
    yield api


class TestIndustryApi:
    """IndustryApi unit test stubs"""

    def test_get_characters_character_id_industry_jobs(self, api):
        """Test case for get_characters_character_id_industry_jobs

        List character industry jobs
        """
        pass

    def test_get_characters_character_id_mining(self, api):
        """Test case for get_characters_character_id_mining

        Character mining ledger
        """
        pass

    def test_get_corporation_corporation_id_mining_extractions(self, api):
        """Test case for get_corporation_corporation_id_mining_extractions

        Moon extraction timers
        """
        pass

    def test_get_corporation_corporation_id_mining_observers(self, api):
        """Test case for get_corporation_corporation_id_mining_observers

        Corporation mining observers
        """
        pass

    def test_get_corporation_corporation_id_mining_observers_observer_id(self, api):
        """Test case for get_corporation_corporation_id_mining_observers_observer_id

        Observed corporation mining
        """
        pass

    def test_get_corporations_corporation_id_industry_jobs(self, api):
        """Test case for get_corporations_corporation_id_industry_jobs

        List corporation industry jobs
        """
        pass

    def test_get_industry_facilities(self, api):
        """Test case for get_industry_facilities

        List industry facilities
        """
        pass

    def test_get_industry_systems(self, api):
        """Test case for get_industry_systems

        List solar system cost indices
        """
        pass
