# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.skills_api import SkillsApi


@pytest.fixture(scope="module")
def api():
    api = SkillsApi()
    yield api


class TestSkillsApi:
    """SkillsApi unit test stubs"""

    def test_get_characters_character_id_attributes(self, api):
        """Test case for get_characters_character_id_attributes

        Get character attributes
        """
        pass

    def test_get_characters_character_id_skillqueue(self, api):
        """Test case for get_characters_character_id_skillqueue

        Get character's skill queue
        """
        pass

    def test_get_characters_character_id_skills(self, api):
        """Test case for get_characters_character_id_skills

        Get character skills
        """
        pass
