# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.sovereignty_api import SovereigntyApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = SovereigntyApi()
    yield api


class TestSovereigntyApi:
    """SovereigntyApi unit test stubs"""

    def test_get_sovereignty_campaigns(self, api):
        """Test case for get_sovereignty_campaigns

        List sovereignty campaigns
        """
        pass

    def test_get_sovereignty_map(self, api):
        """Test case for get_sovereignty_map

        List sovereignty of systems
        """
        pass

    def test_get_sovereignty_structures(self, api):
        """Test case for get_sovereignty_structures

        List sovereignty structures
        """
        pass
