# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.user_interface_api import UserInterfaceApi


@pytest.fixture(scope="module")
def api():
    api = UserInterfaceApi()
    yield api


class TestUserInterfaceApi:
    """UserInterfaceApi unit test stubs"""

    def test_post_ui_autopilot_waypoint(self, api):
        """Test case for post_ui_autopilot_waypoint

        Set Autopilot Waypoint
        """
        pass

    def test_post_ui_openwindow_contract(self, api):
        """Test case for post_ui_openwindow_contract

        Open Contract Window
        """
        pass

    def test_post_ui_openwindow_information(self, api):
        """Test case for post_ui_openwindow_information

        Open Information Window
        """
        pass

    def test_post_ui_openwindow_marketdetails(self, api):
        """Test case for post_ui_openwindow_marketdetails

        Open Market Details
        """
        pass

    def test_post_ui_openwindow_newmail(self, api):
        """Test case for post_ui_openwindow_newmail

        Open New Mail Window
        """
        pass
