# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.fittings_api import FittingsApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = FittingsApi()
    yield api


class TestFittingsApi:
    """FittingsApi unit test stubs"""

    def test_delete_characters_character_id_fittings_fitting_id(self, api):
        """Test case for delete_characters_character_id_fittings_fitting_id

        Delete fitting
        """
        pass

    def test_get_characters_character_id_fittings(self, api):
        """Test case for get_characters_character_id_fittings

        Get fittings
        """
        pass

    def test_post_characters_character_id_fittings(self, api):
        """Test case for post_characters_character_id_fittings

        Create fitting
        """
        pass
