# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.dogma_api import DogmaApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = DogmaApi()
    yield api


class TestDogmaApi:
    """DogmaApi unit test stubs"""

    def test_get_dogma_attributes(self, api):
        """Test case for get_dogma_attributes

        Get attributes
        """
        pass

    def test_get_dogma_attributes_attribute_id(self, api):
        """Test case for get_dogma_attributes_attribute_id

        Get attribute information
        """
        pass

    def test_get_dogma_dynamic_items_type_id_item_id(self, api):
        """Test case for get_dogma_dynamic_items_type_id_item_id

        Get dynamic item information
        """
        pass

    def test_get_dogma_effects(self, api):
        """Test case for get_dogma_effects

        Get effects
        """
        pass

    def test_get_dogma_effects_effect_id(self, api):
        """Test case for get_dogma_effects_effect_id

        Get effect information
        """
        pass
