# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.faction_warfare_api import FactionWarfareApi


@pytest.fixture(scope="module")
def api():
    api = FactionWarfareApi()
    yield api


class TestFactionWarfareApi:
    """FactionWarfareApi unit test stubs"""

    def test_get_characters_character_id_fw_stats(self, api):
        """Test case for get_characters_character_id_fw_stats

        Overview of a character involved in faction warfare
        """
        pass

    def test_get_corporations_corporation_id_fw_stats(self, api):
        """Test case for get_corporations_corporation_id_fw_stats

        Overview of a corporation involved in faction warfare
        """
        pass

    def test_get_fw_leaderboards(self, api):
        """Test case for get_fw_leaderboards

        List of the top factions in faction warfare
        """
        pass

    def test_get_fw_leaderboards_characters(self, api):
        """Test case for get_fw_leaderboards_characters

        List of the top pilots in faction warfare
        """
        pass

    def test_get_fw_leaderboards_corporations(self, api):
        """Test case for get_fw_leaderboards_corporations

        List of the top corporations in faction warfare
        """
        pass

    def test_get_fw_stats(self, api):
        """Test case for get_fw_stats

        An overview of statistics about factions involved in faction warfare
        """
        pass

    def test_get_fw_systems(self, api):
        """Test case for get_fw_systems

        Ownership of faction warfare systems
        """
        pass

    def test_get_fw_wars(self, api):
        """Test case for get_fw_wars

        Data about which NPC factions are at war
        """
        pass
