# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.wallet_api import WalletApi


@pytest.fixture(scope="module")
def api():
    api = WalletApi()
    yield api


class TestWalletApi:
    """WalletApi unit test stubs"""

    def test_get_characters_character_id_wallet(self, api):
        """Test case for get_characters_character_id_wallet

        Get a character's wallet balance
        """
        pass

    def test_get_characters_character_id_wallet_journal(self, api):
        """Test case for get_characters_character_id_wallet_journal

        Get character wallet journal
        """
        pass

    def test_get_characters_character_id_wallet_transactions(self, api):
        """Test case for get_characters_character_id_wallet_transactions

        Get wallet transactions
        """
        pass

    def test_get_corporations_corporation_id_wallets(self, api):
        """Test case for get_corporations_corporation_id_wallets

        Returns a corporation's wallet balance
        """
        pass

    def test_get_corporations_corporation_id_wallets_division_journal(self, api):
        """Test case for get_corporations_corporation_id_wallets_division_journal

        Get corporation wallet journal
        """
        pass

    def test_get_corporations_corporation_id_wallets_division_transactions(self, api):
        """Test case for get_corporations_corporation_id_wallets_division_transactions

        Get corporation wallet transactions
        """
        pass
