# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.routes_api import RoutesApi


@pytest.fixture(scope="module")
def api():
    api = RoutesApi()
    yield api


class TestRoutesApi:
    """RoutesApi unit test stubs"""

    def test_get_route_origin_destination(self, api):
        """Test case for get_route_origin_destination

        Get route
        """
        pass
