# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.alliance_api import AllianceApi


@pytest.fixture(scope="module")
def api():
    api = AllianceApi()
    yield api


class TestAllianceApi:
    """AllianceApi unit test stubs"""

    def test_get_alliances(self, api):
        """Test case for get_alliances

        List all alliances
        """
        pass

    def test_get_alliances_alliance_id(self, api):
        """Test case for get_alliances_alliance_id

        Get alliance information
        """
        pass

    def test_get_alliances_alliance_id_corporations(self, api):
        """Test case for get_alliances_alliance_id_corporations

        List alliance's corporations
        """
        pass

    def test_get_alliances_alliance_id_icons(self, api):
        """Test case for get_alliances_alliance_id_icons

        Get alliance icon
        """
        pass
