# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.loyalty_api import LoyaltyApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = LoyaltyApi()
    yield api


class TestLoyaltyApi:
    """LoyaltyApi unit test stubs"""

    def test_get_characters_character_id_loyalty_points(self, api):
        """Test case for get_characters_character_id_loyalty_points

        Get loyalty points
        """
        pass

    def test_get_loyalty_stores_corporation_id_offers(self, api):
        """Test case for get_loyalty_stores_corporation_id_offers

        List loyalty store offers
        """
        pass
