# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import


class TestErrorLimited:
    """ErrorLimited unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorLimited(self):
        """Test ErrorLimited"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_limited.ErrorLimited()
        pass
