# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.wars_api import WarsApi


@pytest.fixture(scope="module")
def api():
    api = WarsApi()
    yield api


class TestWarsApi:
    """WarsApi unit test stubs"""

    def test_get_wars(self, api):
        """Test case for get_wars

        List wars
        """
        pass

    def test_get_wars_war_id(self, api):
        """Test case for get_wars_war_id

        Get war information
        """
        pass

    def test_get_wars_war_id_killmails(self, api):
        """Test case for get_wars_war_id_killmails

        List kills for a war
        """
        pass
