# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.fleets_api import FleetsApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = FleetsApi()
    yield api


class TestFleetsApi:
    """FleetsApi unit test stubs"""

    def test_delete_fleets_fleet_id_members_member_id(self, api):
        """Test case for delete_fleets_fleet_id_members_member_id

        Kick fleet member
        """
        pass

    def test_delete_fleets_fleet_id_squads_squad_id(self, api):
        """Test case for delete_fleets_fleet_id_squads_squad_id

        Delete fleet squad
        """
        pass

    def test_delete_fleets_fleet_id_wings_wing_id(self, api):
        """Test case for delete_fleets_fleet_id_wings_wing_id

        Delete fleet wing
        """
        pass

    def test_get_characters_character_id_fleet(self, api):
        """Test case for get_characters_character_id_fleet

        Get character fleet info
        """
        pass

    def test_get_fleets_fleet_id(self, api):
        """Test case for get_fleets_fleet_id

        Get fleet information
        """
        pass

    def test_get_fleets_fleet_id_members(self, api):
        """Test case for get_fleets_fleet_id_members

        Get fleet members
        """
        pass

    def test_get_fleets_fleet_id_wings(self, api):
        """Test case for get_fleets_fleet_id_wings

        Get fleet wings
        """
        pass

    def test_post_fleets_fleet_id_members(self, api):
        """Test case for post_fleets_fleet_id_members

        Create fleet invitation
        """
        pass

    def test_post_fleets_fleet_id_wings(self, api):
        """Test case for post_fleets_fleet_id_wings

        Create fleet wing
        """
        pass

    def test_post_fleets_fleet_id_wings_wing_id_squads(self, api):
        """Test case for post_fleets_fleet_id_wings_wing_id_squads

        Create fleet squad
        """
        pass

    def test_put_fleets_fleet_id(self, api):
        """Test case for put_fleets_fleet_id

        Update fleet
        """
        pass

    def test_put_fleets_fleet_id_members_member_id(self, api):
        """Test case for put_fleets_fleet_id_members_member_id

        Move fleet member
        """
        pass

    def test_put_fleets_fleet_id_squads_squad_id(self, api):
        """Test case for put_fleets_fleet_id_squads_squad_id

        Rename fleet squad
        """
        pass

    def test_put_fleets_fleet_id_wings_wing_id(self, api):
        """Test case for put_fleets_fleet_id_wings_wing_id

        Rename fleet wing
        """
        pass
