# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import


class TestBadRequest:
    """BadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadRequest(self):
        """Test BadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bad_request.BadRequest()
        pass
