# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.killmails_api import KillmailsApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = KillmailsApi()
    yield api


class TestKillmailsApi:
    """KillmailsApi unit test stubs"""

    def test_get_characters_character_id_killmails_recent(self, api):
        """Test case for get_characters_character_id_killmails_recent

        Get a character's recent kills and losses
        """
        pass

    def test_get_corporations_corporation_id_killmails_recent(self, api):
        """Test case for get_corporations_corporation_id_killmails_recent

        Get a corporation's recent kills and losses
        """
        pass

    def test_get_killmails_killmail_id_killmail_hash(self, api):
        """Test case for get_killmails_killmail_id_killmail_hash

        Get a single killmail
        """
        pass
