# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.location_api import LocationApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = LocationApi()
    yield api


class TestLocationApi:
    """LocationApi unit test stubs"""

    def test_get_characters_character_id_location(self, api):
        """Test case for get_characters_character_id_location

        Get character location
        """
        pass

    def test_get_characters_character_id_online(self, api):
        """Test case for get_characters_character_id_online

        Get character online
        """
        pass

    def test_get_characters_character_id_ship(self, api):
        """Test case for get_characters_character_id_ship

        Get current ship
        """
        pass
