# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.planetary_interaction_api import (
    PlanetaryInteractionApi,
)


@pytest.fixture(scope="module")
def api():
    api = PlanetaryInteractionApi()
    yield api


class TestPlanetaryInteractionApi:
    """PlanetaryInteractionApi unit test stubs"""

    def test_get_characters_character_id_planets(self, api):
        """Test case for get_characters_character_id_planets

        Get colonies
        """
        pass

    def test_get_characters_character_id_planets_planet_id(self, api):
        """Test case for get_characters_character_id_planets_planet_id

        Get colony layout
        """
        pass

    def test_get_corporations_corporation_id_customs_offices(self, api):
        """Test case for get_corporations_corporation_id_customs_offices

        List corporation customs offices
        """
        pass

    def test_get_universe_schematics_schematic_id(self, api):
        """Test case for get_universe_schematics_schematic_id

        Get schematic information
        """
        pass
