# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.models.forbidden import Forbidden
from eve_tools.swagger_client.rest import ApiException


class TestForbidden:
    """Forbidden unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForbidden(self):
        """Test Forbidden"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.forbidden.Forbidden()
        pass
