# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.mail_api import MailApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = MailApi()
    yield api


class TestMailApi:
    """MailApi unit test stubs"""

    def test_delete_characters_character_id_mail_labels_label_id(self, api):
        """Test case for delete_characters_character_id_mail_labels_label_id

        Delete a mail label
        """
        pass

    def test_delete_characters_character_id_mail_mail_id(self, api):
        """Test case for delete_characters_character_id_mail_mail_id

        Delete a mail
        """
        pass

    def test_get_characters_character_id_mail(self, api):
        """Test case for get_characters_character_id_mail

        Return mail headers
        """
        pass

    def test_get_characters_character_id_mail_labels(self, api):
        """Test case for get_characters_character_id_mail_labels

        Get mail labels and unread counts
        """
        pass

    def test_get_characters_character_id_mail_lists(self, api):
        """Test case for get_characters_character_id_mail_lists

        Return mailing list subscriptions
        """
        pass

    def test_get_characters_character_id_mail_mail_id(self, api):
        """Test case for get_characters_character_id_mail_mail_id

        Return a mail
        """
        pass

    def test_post_characters_character_id_mail(self, api):
        """Test case for post_characters_character_id_mail

        Send a new mail
        """
        pass

    def test_post_characters_character_id_mail_labels(self, api):
        """Test case for post_characters_character_id_mail_labels

        Create a mail label
        """
        pass

    def test_put_characters_character_id_mail_mail_id(self, api):
        """Test case for put_characters_character_id_mail_mail_id

        Update metadata about a mail
        """
        pass
