# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from eve_tools.swagger_client.api.universe_api import UniverseApi


@pytest.fixture(scope="module")
def api():
    api = UniverseApi()
    yield api


class TestUniverseApi:
    """UniverseApi unit test stubs"""

    def test_get_universe_ancestries(self, api):
        """Test case for get_universe_ancestries

        Get ancestries
        """
        assert api.get_universe_ancestries()[0]["bloodline_id"] == 5

    def test_get_universe_asteroid_belts_asteroid_belt_id(self, api):
        """Test case for get_universe_asteroid_belts_asteroid_belt_id

        Get asteroid belt information
        """
        pass

    def test_get_universe_bloodlines(self, api):
        """Test case for get_universe_bloodlines

        Get bloodlines
        """
        pass

    def test_get_universe_categories(self, api):
        """Test case for get_universe_categories

        Get item categories
        """
        pass

    def test_get_universe_categories_category_id(self, api):
        """Test case for get_universe_categories_category_id

        Get item category information
        """
        pass

    def test_get_universe_constellations(self, api):
        """Test case for get_universe_constellations

        Get constellations
        """
        pass

    def test_get_universe_constellations_constellation_id(self, api):
        """Test case for get_universe_constellations_constellation_id

        Get constellation information
        """
        pass

    def test_get_universe_factions(self, api):
        """Test case for get_universe_factions

        Get factions
        """
        pass

    def test_get_universe_graphics(self, api):
        """Test case for get_universe_graphics

        Get graphics
        """
        pass

    def test_get_universe_graphics_graphic_id(self, api):
        """Test case for get_universe_graphics_graphic_id

        Get graphic information
        """
        pass

    def test_get_universe_groups(self, api):
        """Test case for get_universe_groups

        Get item groups
        """
        pass

    def test_get_universe_groups_group_id(self, api):
        """Test case for get_universe_groups_group_id

        Get item group information
        """
        pass

    def test_get_universe_moons_moon_id(self, api):
        """Test case for get_universe_moons_moon_id

        Get moon information
        """
        pass

    def test_get_universe_planets_planet_id(self, api):
        """Test case for get_universe_planets_planet_id

        Get planet information
        """
        pass

    def test_get_universe_races(self, api):
        """Test case for get_universe_races

        Get character races
        """
        pass

    def test_get_universe_regions(self, api):
        """Test case for get_universe_regions

        Get regions
        """
        pass

    def test_get_universe_regions_region_id(self, api):
        """Test case for get_universe_regions_region_id

        Get region information
        """
        pass

    def test_get_universe_stargates_stargate_id(self, api):
        """Test case for get_universe_stargates_stargate_id

        Get stargate information
        """
        pass

    def test_get_universe_stars_star_id(self, api):
        """Test case for get_universe_stars_star_id

        Get star information
        """
        pass

    def test_get_universe_stations_station_id(self, api):
        """Test case for get_universe_stations_station_id

        Get station information
        """
        pass

    def test_get_universe_structures(self, api):
        """Test case for get_universe_structures

        List all public structures
        """
        pass

    def test_get_universe_structures_structure_id(self, api):
        """Test case for get_universe_structures_structure_id

        Get structure information
        """
        pass

    def test_get_universe_system_jumps(self, api):
        """Test case for get_universe_system_jumps

        Get system jumps
        """
        pass

    def test_get_universe_system_kills(self, api):
        """Test case for get_universe_system_kills

        Get system kills
        """
        pass

    def test_get_universe_systems(self, api):
        """Test case for get_universe_systems

        Get solar systems
        """
        pass

    def test_get_universe_systems_system_id(self, api):
        """Test case for get_universe_systems_system_id

        Get solar system information
        """
        pass

    def test_get_universe_types(self, api):
        """Test case for get_universe_types

        Get types
        """
        pass

    def test_get_universe_types_type_id(self, api):
        """Test case for get_universe_types_type_id

        Get type information
        """
        pass

    def test_post_universe_ids(self, api):
        """Test case for post_universe_ids

        Bulk names to IDs
        """
        pass

    def test_post_universe_names(self, api):
        """Test case for post_universe_names

        Get names and categories for a set of IDs
        """
        pass
