# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 1.7.15

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from tests import context

import pytest

from eve_tools import swagger_client
from eve_tools.swagger_client.api.insurance_api import InsuranceApi
from eve_tools.swagger_client.rest import ApiException


@pytest.fixture(scope="module")
def api():
    api = InsuranceApi()
    yield api


class TestInsuranceApi:
    """InsuranceApi unit test stubs"""

    def test_get_insurance_prices(self, api):
        """Test case for get_insurance_prices

        List insurance levels
        """
        pass
